# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0


name: Sync headers from upstream repository (brew)



on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish the headers'
        required: false
        default: false
        type: boolean

  schedule:
    - cron: "0 2 * * 0" # Runs at 02:00 UTC every Sunday

jobs:
  sync-headers:
    name: "Sync headers from upstream repository (brew)"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install dependencies
        run: pip install build
      
      - name: Enable brew
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install brew
        run: |
           brew install nlohmann-json boost eigen msgpack-cxx

      - name: copy headers
        run: |
          rm -rf src/pgm_build_dependencies/nlohmann_json/*
          rm -rf src/pgm_build_dependencies/boost/*
          rm -rf src/pgm_build_dependencies/eigen/*
          rm -rf src/pgm_build_dependencies/msgpack_cxx/*
          cp -r /home/linuxbrew/.linuxbrew/Cellar/nlohmann-json/*/* src/pgm_build_dependencies/nlohmann_json/
          cp -r /home/linuxbrew/.linuxbrew/Cellar/boost/*/* src/pgm_build_dependencies/boost/
          cp -r /home/linuxbrew/.linuxbrew/Cellar/eigen/*/* src/pgm_build_dependencies/eigen/
          cp -r /home/linuxbrew/.linuxbrew/Cellar/msgpack-cxx/*/* src/pgm_build_dependencies/msgpack_cxx/
          find src/ \( -type f ! -exec grep -Iq . {} \; -o -type l \) -delete
          ls src/pgm_build_dependencies/nlohmann_json/
          ls src/pgm_build_dependencies/boost/
          ls src/pgm_build_dependencies/eigen/
          ls src/pgm_build_dependencies/msgpack_cxx/

      - name: License scan - eigen headers
        uses: fossology/fossology-action@v1
        with:
          scan_mode: repo
          scanners: 'nomos ojo copyright keyword'
          report_format: 'SPDX_JSON'
          scan_dir: src/pgm_build_dependencies/eigen/

      - name: Upload Scan Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fossology scan results
          path: results/

      - name: build wheel
        run: |
          python -m build --wheel --outdir dist
          ls dist/
          echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Commit and push changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update the headers
          commit_options: '--signoff'
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>

      - name: publish
        if: ${{ inputs.force_publish || steps.commit.outputs.changes_detected == 'true'  }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: dist/*.whl
          draft: false
          prerelease: false
          target_commitish: ${{ github.sha }}
